### ISSUE TITLE
can't get the correct result

### ISSUE THREAD

**Issue by SydOps** [FloeDesignTechnologies/ansible-haproxy#43]
my groups_var file:
```
haproxy_listen:
  - name: ssl
    bind: "{{ ansible_default_ipv4.address }}"
    ssl:
      cert: /etc/pki/tls/certs/ssl.pem no-sslv3
```
But I got this:

```
listen ssl
   bind 1 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind 0 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind . ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind 1 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind . ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind 1 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind . ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
   bind 2 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
```

should be: 
```
listen ssl
   bind 10.1.1.2 ssl crt /etc/pki/tls/certs/ssl.pem no-sslv3
```

**Comment by SydOps** [comment]
ic. the bind has to be array

```
haproxy_listen:
  - name: ssl
    bind: 
       - "{{ ansible_default_ipv4.address }}"
    ssl:
      cert: /etc/pki/tls/certs/ssl.pem no-sslv3
```
